// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://elkejpsafdbicudpziuk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVsa2VqcHNhZmRiaWN1ZHB6aXVrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIwNjIwMDQsImV4cCI6MjA1NzYzODAwNH0.ZPZpeZpvLkDwQclHHHdxzsa_rJmJanRy2_fvU5qxGdE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);